version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - db
    restart: on-failure
    links:
      - "db:database"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/spherity
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    restart: always