version: '3.9'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: on-failure
    links:
      - 'db:database'
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/spherity
      ENCRYPT_KEY: 232f150296ffd446fc0b39fa32d1c1d42c2e232ccd3203df729b7f3c3c63a5da2
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: spherity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    restart: always
